Update to svelte 5
CSIS-iLab/energy-database pull request #45
Opened 2024-10-25 15:24 UTC by jdromero88

2024-10-29 13:06 UTC, urchykli requested changes
Great work on this, Jose! In addition to the things I noted to delete, if we are no longer using Rollup, let's remove it from the README. Thanks for your hard work on this!

2024-10-29 13:06 UTC, urchykli commented on src/lib/Table.svelte
> +  // console.log(e)
Let's delete this commented out console log.

2024-10-29 13:06 UTC, urchykli commented on src/lib/Table.svelte
> +    // row.isOpen = row.isOpen ? true : !row.isOpen
If we don't need this let's delete it.

2024-10-29 13:06 UTC, urchykli commented on src/scss/components/_table.scss
> +      // max-height: 0px;
If we don't need this let's delete it.

2024-10-29 13:06 UTC, urchykli commented on src/scss/components/_table.scss
> +// }
If we don't need this let's delete it.

2024-10-29 15:49 UTC, jdromero88 commented
I removed all the commented lines and add a function to sort the dropdowns alphabetically.

2024-10-30 13:52 UTC, urchykli requested changes
Thanks for cleaning this up, Jose! There's one more commented out style declaration that needs to be deleted and then you can merge!

2024-10-30 13:52 UTC, urchykli commented on src/scss/components/_table.scss
> +      // max-height: 0px;
This commented out code is still in the file - do we need it?

2024-10-30 14:53 UTC, merged